alertmanager:
  enabled: true

grafana:
  enabled: true
  adminPassword: ${admin_password}

  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: ${grafana_certificate}
      alb.ingress.kubernetes.io/group.name: ${grafana_group_name}
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/security-groups: ""
      alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/subnets: ${grafana_subnets}
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/success-codes: '200,302'
    hosts:
      - "${grafana_domain}"

    ingressClassName: alb

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

  persistence:
    enabled: true
    storageClassName: gp2
    size: 1Gi

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 30d
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 100m
        memory: 512Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: ${prometheus_certificate}
      alb.ingress.kubernetes.io/group.name: ${prometheus_group_name}
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/security-groups: ""
      alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/subnets: ${prometheus_subnets}
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/success-codes: '200,302'
    hosts:
      - "${prometheus_domain}"

    ingressClassName: alb
