{
 "title": "Izy / Environment Status / logs - Patrick",
 "tags": [ "Izy" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "logs",
   "gridPos": { "h": 30, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"apps\", job=\"fluentbit\"} !~ `.*\\s200[\\s\\W].*` | json | line_format \"{{printf \\\"%20s\\\" .app_kubernetes_io_name}}   {{.log}}\""
    }
   ]
  },
  {
   "title": "All running pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Running'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Pending'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Killed pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"integrations/kubernetes/eventhandler\", namespace=\"apps\"} |~ `Killing` [$__range])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Active connections",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "ActiveConnectionCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(ActiveConnectionCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Avg response time",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Requests",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "RequestCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(RequestCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster:node_cpu:ratio_rate5m{}",
     "legendFormat": "Cluster CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "Cluster Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "RDS Writer conn...",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DatabaseConnections", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "WRITER" }, "property": { "name": "Role", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "production-pg-cluster" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DatabaseConnections) FROM \"AWS/RDS\" WHERE Role = 'WRITER' AND DBClusterIdentifier = 'production-pg-cluster'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "RDS Writer CPU",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "CPUUtilization", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "WRITER" }, "property": { "name": "Role", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "production-pg-cluster" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(CPUUtilization) FROM \"AWS/RDS\" WHERE Role = 'WRITER' AND DBClusterIdentifier = 'production-pg-cluster'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "RDS Writer Freeable Memory",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "FreeableMemory", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "WRITER" }, "property": { "name": "Role", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "production-pg-cluster" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(FreeableMemory) FROM \"AWS/RDS\" WHERE Role = 'WRITER' AND DBClusterIdentifier = 'production-pg-cluster'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Target 2XX count",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Target 4XX count",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "HTTPCode_Target_4XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(HTTPCode_Target_4XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Target 5XX count",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "HTTPCode_Target_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(HTTPCode_Target_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsproduction-824e1f1fdc/3ad74d56402d6adb'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "adhoc",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-adhoc-b9d47bf3a0/d424cb54df21280b"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-adhoc-b9d47bf3a0/d424cb54df21280b'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "booking",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-booking-712ba765a0/a465d9dfede551fd"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-booking-712ba765a0/a465d9dfede551fd'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "canteen",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-canteen-08860fcab2/c2b1388c32cb9c29"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-canteen-08860fcab2/c2b1388c32cb9c29'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "conferencemeal",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-conferen-01e890877d/662b15b07b4af2a4"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-conferen-01e890877d/662b15b07b4af2a4'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "entities",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-entities-751c8eb87c/64f8b51e63be7107"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-entities-751c8eb87c/64f8b51e63be7107'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "filehandler",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-filehand-83b4f3ccb5/413515885d7f7c69"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-filehand-83b4f3ccb5/413515885d7f7c69'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "insight",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-insight-da9a6a3d8a/01049250ea22c842"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-insight-c3a8d91a16/326ec7dd4d617464'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "invoice",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-invoice-d395c3e333/8ca20c1879e60039"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-invoice-d395c3e333/8ca20c1879e60039'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "izyportal",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-izyporta-1a3608c502/c8ca27867039084d"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-izyporta-1a3608c502/c8ca27867039084d'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "kiosk",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-kiosk-fa14c54256/e03a58935bb61f24"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-kiosk-fa14c54256/e03a58935bb61f24'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "meetingroomdisplay",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-meetingr-e59bafa06e/e8d765d5d3b7d866"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-meetingr-e59bafa06e/e8d765d5d3b7d866'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "microsoftintegration",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-microsof-c69f4a7f87/1db6d735e1ce5bea"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-microsof-f1ae2f085c/e7410481c3c4ed1d'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "news",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-news-7a08f8a698/d5cbe1f1d431a3ef"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-news-7a08f8a698/d5cbe1f1d431a3ef'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "notification",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-notifica-7305ec9b37/45f62ce260d9940a"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-notifica-7305ec9b37/45f62ce260d9940a'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "payment",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-payment-418cd6e7a8/7c90ef4f496c9d6a"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-payment-418cd6e7a8/7c90ef4f496c9d6a'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "publicapi",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-publicap-92a31d96ad/f935b0481c47d310"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-publicap-9a584a30f8/a5da88b70986146e'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "redshift",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-redshift-871506bb42/c15c1a89c375b334"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-redshift-871506bb42/c15c1a89c375b334'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "reports",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-reports-edf63ccdef/09e79525cf24ee85"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-reports-edf63ccdef/09e79525cf24ee85'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "scheduler",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-schedule-9da5c2d406/77071c7240762107"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-schedule-1eda1a65eb/61b60df28bacb218'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "tickets",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-tickets-bd460031b5/f1d42bdacfa92114"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-tickets-bce8d2fdc7/f9b599cafd0895a5'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "usermanagement",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-north-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-usermana-46627f3057/8ca2ea688d428f4d"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-usermana-46627f3057/8ca2ea688d428f4d'",
     "statistic": "Average"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 16, "y": 21 }, "fieldConfig": { "defaults": { "unit": "percent" } }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 18, "y": 21 }, "fieldConfig": { "defaults": { "unit": "percent" } }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  }
 ]
}