{
 "title": "Izy / Environment Status / logs - Patrick",
 "tags": [ "Izy" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "logs",
   "gridPos": { "h": 30, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"apps\", job=\"fluentbit\"} !~ `.*\\s200[\\s\\W].*` | json | line_format \"{{printf \\\"%20s\\\" .app_kubernetes_io_name}}   {{.log}}\""
    }
   ]
  },
  {
   "title": "All running pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Running'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Pending'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Killed pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"integrations/kubernetes/eventhandler\", namespace=\"apps\"} |~ `Killing` [$__range])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Active connections",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "ActiveConnectionCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(ActiveConnectionCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Avg response time",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Requests",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "RequestCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(RequestCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster:node_cpu:ratio_rate5m{}",
     "legendFormat": "Cluster CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "Cluster Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "RDS Writer conn...",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DatabaseConnections", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "WRITER" }, "property": { "name": "Role", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "sandbox-db" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DatabaseConnections) FROM \"AWS/RDS\" WHERE Role = 'WRITER' AND DBClusterIdentifier = 'sandbox-db'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "RDS Writer CPU",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "CPUUtilization", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "WRITER" }, "property": { "name": "Role", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "sandbox-db" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(CPUUtilization) FROM \"AWS/RDS\" WHERE Role = 'WRITER' AND DBClusterIdentifier = 'sandbox-db'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "RDS Writer Freeable Memory",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "FreeableMemory", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "WRITER" }, "property": { "name": "Role", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "sandbox-db" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(FreeableMemory) FROM \"AWS/RDS\" WHERE Role = 'WRITER' AND DBClusterIdentifier = 'sandbox-db'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Target 2XX count",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Target 4XX count",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "HTTPCode_Target_4XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(HTTPCode_Target_4XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Target 5XX count",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "HTTPCode_Target_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(HTTPCode_Target_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appssandbox-135efc7c58/5e5b2f0c9dc26af4'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "adhoc",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-adhoc-9da90313d9/1c0713c8441d3bac"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-adhoc-9da90313d9/1c0713c8441d3bac'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "booking",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-booking-49cbcaec63/8ae2c6aa6259b58c"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-booking-49cbcaec63/8ae2c6aa6259b58c'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "canteen",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-canteen-4c825255d0/45fa99eec74c39d3"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-canteen-4c825255d0/45fa99eec74c39d3'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "conferencemeal",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-conferen-f4fe8e13da/26d2ede9d0200a74"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-conferen-f4fe8e13da/26d2ede9d0200a74'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "entities",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-entities-3a6376eb63/9287798cb7d1035c"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-entities-3a6376eb63/9287798cb7d1035c'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "filehandler",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "insight",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-insight-da9a6a3d8a/01049250ea22c842"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-insight-da9a6a3d8a/01049250ea22c842'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "invoice",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-invoice-818202a415/24adc69f905e4d9a"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-invoice-818202a415/24adc69f905e4d9a'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "izyportal",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-izyporta-afb180a5c3/3fab2e90337c2de3"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-izyporta-afb180a5c3/3fab2e90337c2de3'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "kiosk",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-kiosk-b4c9cc8f67/7241726c5903d548"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-kiosk-b4c9cc8f67/7241726c5903d548'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "meetingroomdisplay",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-meetingr-e59bafa06e/e8d765d5d3b7d866"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-meetingr-e59bafa06e/e8d765d5d3b7d866'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "microsoftintegration",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-microsof-c69f4a7f87/1db6d735e1ce5bea"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-microsof-c69f4a7f87/1db6d735e1ce5bea'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "news",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-news-27334a188a/71951e9a93829abc"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-news-27334a188a/71951e9a93829abc'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "notification",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-notifica-1afc52a98e/2635e2a47579d3e8"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-notifica-1afc52a98e/2635e2a47579d3e8'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "payment",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-payment-e0dd86ff21/94f4d4f02ac1fbe7"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-payment-e0dd86ff21/94f4d4f02ac1fbe7'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "publicapi",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-publicap-92a31d96ad/f935b0481c47d310"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-publicap-92a31d96ad/f935b0481c47d310'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "redshift",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-redshift-871506bb42/c15c1a89c375b334"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-redshift-871506bb42/c15c1a89c375b334'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "reports",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-reports-edf31a2694/10cf961e9b47c48e"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-reports-edf31a2694/10cf961e9b47c48e'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "scheduler",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-schedule-9da5c2d406/77071c7240762107"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-schedule-9da5c2d406/77071c7240762107'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "tickets",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-tickets-bd460031b5/f1d42bdacfa92114"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-tickets-bd460031b5/f1d42bdacfa92114'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "usermanagement",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-usermana-ec3aa0e3a5/1d4eaa225a5dd9d2"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-usermana-ec3aa0e3a5/1d4eaa225a5dd9d2'",
     "statistic": "Average"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 16, "y": 21 }, "fieldConfig": { "defaults": { "unit": "percent" } }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 18, "y": 21 }, "fieldConfig": { "defaults": { "unit": "percent" } }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  }
 ]
}