{
 "title": "Izy / Environment Status",
 "tags": [ "Izy" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster:node_cpu:ratio_rate5m{}",
     "legendFormat": "Cluster CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "Cluster Memory"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All running pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Running'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Pending'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Killed pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"integrations/kubernetes/eventhandler\", namespace=\"apps\"} |~ `Killing` [$__range])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "RDS Writer CPU",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "CPUUtilization", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "WRITER" }, "property": { "name": "Role", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "staging-db" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(CPUUtilization) FROM \"AWS/RDS\" WHERE Role = 'WRITER' AND DBClusterIdentifier = 'staging-db'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "RDS Writer conn...",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DatabaseConnections", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "WRITER" }, "property": { "name": "Role", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "staging-db" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DatabaseConnections) FROM \"AWS/RDS\" WHERE Role = 'WRITER' AND DBClusterIdentifier = 'staging-db'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "RDS Writer Freeable Memory",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "FreeableMemory", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "WRITER" }, "property": { "name": "Role", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "staging-db" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(FreeableMemory) FROM \"AWS/RDS\" WHERE Role = 'WRITER' AND DBClusterIdentifier = 'staging-db'",
     "statistic": "Average"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 }, "fieldConfig": { "defaults": { "unit": "percent" } }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 }, "fieldConfig": { "defaults": { "unit": "percent" } }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 }, "fieldConfig": { "defaults": { "unit": "percent" } }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Avg response time",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Requests",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "RequestCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(RequestCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Active connections",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "ActiveConnectionCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(ActiveConnectionCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Target 2XX count",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Target 4XX count",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "HTTPCode_Target_4XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(HTTPCode_Target_4XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "Target 5XX count",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "HTTPCode_Target_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(HTTPCode_Target_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/k8s-appsstaging-b6effce976/ea828a2c5acdb7c0'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "grafana-polystat-panel",
   "description": "Running pods",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "namespace_workload_pod:kube_pod_owner:relabel{namespace=\"apps\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"apps\",phase=\"Running\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "adhoc",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-adhoc-15f21ce5c4/428d84b0b4b62b65"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-adhoc-15f21ce5c4/428d84b0b4b62b65'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "booking",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-booking-46b8b530e3/d4e93fe481bca260"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-booking-46b8b530e3/d4e93fe481bca260'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "canteen",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-canteen-8e5c80b465/acc8488a06bd66af"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-canteen-8e5c80b465/acc8488a06bd66af'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "conferencemeal",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-conferen-b5b8ab583a/d6f0714def0ddca5"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-conferen-b5b8ab583a/d6f0714def0ddca5'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "entities",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-entities-15464d20fb/907e5303dca66d10"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-entities-15464d20fb/907e5303dca66d10'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "filehandler",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-filehand-33da9bd1e5/1230df49955c73bf"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-filehand-33da9bd1e5/1230df49955c73bf'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "grafana-polystat-panel",
   "description": "4XX responses",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"apps\"} |~ \".*(HTTP/1.1 4\\\\d\\\\d).*\" | __error__=`` [$__range])"
    },
    {
     "expr": "label_replace(count by(workload) (namespace_workload_pod:kube_pod_owner:relabel{namespace=\"apps\"}), \"app_kubernetes_io_name\", \"$1\", \"workload\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "count_over_time({namespace=\"apps\"} |~ \".*(HTTP/1.1 \\\\d\\\\d\\\\d).*\" | __error__=`` [$__range])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "insight",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-insight-da9a6a3d8a/01049250ea22c842"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-insight-6f8f438618/e64e5e7d53fa655a'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "invoice",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-invoice-c8a2e3b36a/cb68c5d42362065b"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-invoice-c8a2e3b36a/cb68c5d42362065b'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "izyportal",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-izyporta-1b9c757858/1d4cfdce77993f2b"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-izyporta-1b9c757858/1d4cfdce77993f2b'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "kiosk",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-kiosk-fad23e4cb4/f4c05855cd71209e"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-kiosk-fad23e4cb4/f4c05855cd71209e'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "meetingroomdisplay",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-meetingr-e59bafa06e/e8d765d5d3b7d866"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-meetingr-0561718664/17997c386be0ae5d'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "microsoftintegration",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-microsof-c69f4a7f87/1db6d735e1ce5bea"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-microsof-bfb2798d9f/773721ab30df5640'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "news",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-news-ba39ccccb5/ffcaf533abc8675a"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-news-ba39ccccb5/ffcaf533abc8675a'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "notification",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-notifica-5aecb50a7f/df74885c6cc70902"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-notifica-5aecb50a7f/df74885c6cc70902'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "payment",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-payment-f9f4a83e0a/480bdd4fe4b3011c"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-payment-f9f4a83e0a/480bdd4fe4b3011c'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "publicapi",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-publicap-92a31d96ad/f935b0481c47d310"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-publicap-92a31d96ad/f935b0481c47d310'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "redshift",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-redshift-871506bb42/c15c1a89c375b334"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-redshift-'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "reports",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-reports-2a7c15762d/8083bb1cdc9ba3ea"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-reports-2a7c15762d/8083bb1cdc9ba3ea'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "grafana-polystat-panel",
   "description": "5XX responses",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"apps\"} |~ \".*(HTTP/1.1 5\\\\d\\\\d).*\" | __error__=`` [$__range])"
    },
    {
     "expr": "label_replace(count by(workload) (namespace_workload_pod:kube_pod_owner:relabel{namespace=\"apps\"}), \"app_kubernetes_io_name\", \"$1\", \"workload\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "count_over_time({namespace=\"apps\"} |~ \".*(HTTP/1.1 \\\\d\\\\d\\\\d).*\" | __error__=`` [$__range])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "scheduler",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-schedule-9da5c2d406/77071c7240762107"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-schedule-8164987b2f/5583e7a66582f8bf'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "tickets",
     "metricEditorMode": 1,
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-tickets-bd460031b5/f1d42bdacfa92114"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-tickets-b6f1cae76a/83b0452156e884b1'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": {
      "TargetGroup": "targetgroup/k8s-apps-filehand-cabc769c8b/f28de75259681474"
     },
     "label": "usermanagement",
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "targetgroup/k8s-apps-usermana-bd1e1f9a2b/ddacecc5422fa625"
         },
         "property": { "name": "TargetGroup", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM \"AWS/ApplicationELB\" WHERE TargetGroup = 'targetgroup/k8s-apps-usermana-bd1e1f9a2b/ddacecc5422fa625'",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=\"apps\", job=\"fluentbit\"} !~ `.*\\s200[\\s\\W].*` | json | line_format \"{{printf \\\"%20s\\\" .app_kubernetes_io_name}}   {{.log}}\""
    }
   ]
  },
  { "type": "alertlist", "gridPos": { "h": 13, "w": 7, "x": 17, "y": 18 } }
 ]
}