{
 "title": "Izy / Microservices Status",
 "description": "This is a modern 'Pods View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [ "Izy" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "microservice",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"apps\"},workload)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{workload=\"$microservice\"}, pod)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container=\"$microservice\", pod=~\"$pod\"}[$__rate_interval])) by (container)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "CPU Requests usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"$microservice\", pod=~\"$pod\"}[$__rate_interval])) / sum(kube_pod_container_resource_requests{container=\"$microservice\", pod=~\"$pod\", unit=\"core\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limits usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"$microservice\", pod=~\"$pod\"}[$__rate_interval])) / sum(kube_pod_container_resource_limits{container=\"$microservice\", pod=~\"$pod\", unit=\"core\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit bandwidth",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (container)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Receive bandwidth",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (container)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Running', pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"$pod\", unit=\"core\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$pod\", unit=\"core\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"$pod\", unit=\"byte\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$pod\", unit=\"byte\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!=\"\", container!=\"POD\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", image!=\"\", container!=\"POD\"}) by (pod)"
    },
    {
     "expr": "kube_pod_info{pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{image!=\"\", container=\"$microservice\", pod=~\"$pod\"}) by (container)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container=\"$microservice\", pod=~\"$pod\", unit=\"byte\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requests usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"$microservice\", pod=~\"$pod\"}) / sum(kube_pod_container_resource_requests{container=\"$microservice\", pod=~\"$pod\", unit=\"byte\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limits usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"$microservice\", pod=~\"$pod\", image!=\"\"}) / sum(kube_pod_container_resource_limits{container=\"$microservice\", pod=~\"$pod\", unit=\"byte\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Killed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate({job=\"integrations/kubernetes/eventhandler\"} |~ `$microservice` |~ `Killing` [$__interval]))"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Running', pod=~\"$pod\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "count_over_time({job=\"integrations/kubernetes/eventhandler\", name=\"$pod\"} |~ \"Killing\" [$__interval])",
     "legendFormat": "Killed"
    }
   ]
  },
  {
   "title": "Log entries other than HTTP 200",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "count_over_time({pod=~\"$pod\"} !~ `.*\\s200[\\s\\W].*`[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=\"apps\", pod=~\"$pod\", job=\"fluentbit\"} !~ `.*\\s200[\\s\\W].*` | json | line_format \"{{printf \\\"%20s\\\" .kubernetes_pod_name}}   {{.log}}\" "
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{namespace=\"apps\", pod=~\"$pod\", job=\"fluentbit\"} |~ `\\s200[\\s\\W]` | json | line_format \"{{printf \\\"%20s\\\" .kubernetes_pod_name}}   {{.log}}\" "
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container=\"$microservice\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{pod=~\"$pod\", image!=\"\", container!=\"POD\"}) by (pod)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU Usage / Requests & Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"$microservice\", pod=~\"$pod\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_requests{container=\"$microservice\", pod=~\"$pod\", unit=\"core\"}) by (pod)",
     "legendFormat": "{{pod}} Requests"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"$microservice\", pod=~\"$pod\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_limits{container=\"$microservice\", pod=~\"$pod\", unit=\"core\"}) by (pod)",
     "legendFormat": "{{pod}} Limits"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests & Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"$microservice\", pod=~\"$pod\"}) by (pod) / sum(kube_pod_container_resource_requests{container=\"$microservice\", pod=~\"$pod\", unit=\"byte\"}) by (pod)",
     "legendFormat": "{{pod}} Requests"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"$microservice\", pod=~\"$pod\"}) by (pod) / sum(kube_pod_container_resource_limits{container=\"$microservice\", pod=~\"$pod\", unit=\"byte\"}) by (pod)",
     "legendFormat": "{{pod}} Limits"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Network - Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Received {{pod}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Transmitted {{pod}}"
    }
   ]
  },
  {
   "title": "Network - Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Received {{pod}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Transmitted {{pod}}"
    }
   ]
  },
  {
   "title": "Network - Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Received {{pod}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_errors_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Transmitted {{pod}}"
    }
   ]
  },
  {
   "title": "Network - Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Received {{pod}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Transmitted {{pod}}"
    }
   ]
  }
 ]
}